"""assignment_id_ondelete_set_null

Revision ID: 1674fb9e6538
Revises: 1bfc371fad5b
Create Date: 2026-08-13 16:54:26.160623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1674fb9e6538'
down_revision: Union[str, Sequence[str], None] = '1bfc371fad5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('production_task_line_reports_assignment_id_fkey'), 'production_task_line_reports', type_='foreignkey')
    op.create_foreign_key(None, 'production_task_line_reports', 'production_task_line_assignments', ['assignment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_task_line_reports', type_='foreignkey')
    op.create_foreign_key(op.f('production_task_line_reports_assignment_id_fkey'), 'production_task_line_reports', 'production_task_line_assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###
