"""Настройки: ячейки штрипса, порог залежи, шаблон заявки

Revision ID: 178cf5721756
Revises: ca87c64dd8f3
Create Date: 2026-08-10 08:13:56.798578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178cf5721756'
down_revision: Union[str, Sequence[str], None] = 'ca87c64dd8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default добавлен вручную — иначе NOT NULL упадёт на уже
    # существующей строке-синглтоне calc_settings (id=1).
    op.add_column('calc_settings', sa.Column('cells_per_strip_shelf', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('calc_settings', sa.Column('stale_threshold_days', sa.Integer(), nullable=False, server_default='60'))
    op.add_column(
        'calc_settings',
        sa.Column(
            'shortage_note_template',
            sa.String(length=255),
            nullable=False,
            server_default='Нехватка по плану: {material}, {color}, {thickness} мм — требуется ещё {shortage_m2} м²',
        ),
    )
    op.alter_column('calc_settings', 'cells_per_strip_shelf', server_default=None)
    op.alter_column('calc_settings', 'stale_threshold_days', server_default=None)
    op.alter_column('calc_settings', 'shortage_note_template', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calc_settings', 'shortage_note_template')
    op.drop_column('calc_settings', 'stale_threshold_days')
    op.drop_column('calc_settings', 'cells_per_strip_shelf')
    # ### end Alembic commands ###
