"""assignment_id_na_otchete_order_id_na_zadanii

Revision ID: 1bfc371fad5b
Revises: d7203067069a
Create Date: 2026-08-13 13:15:25.667819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfc371fad5b'
down_revision: Union[str, Sequence[str], None] = 'd7203067069a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_task_line_reports', sa.Column('assignment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production_task_line_reports', 'production_task_line_assignments', ['assignment_id'], ['id'])
    op.add_column('production_tasks', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production_tasks', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_tasks', type_='foreignkey')
    op.drop_column('production_tasks', 'order_id')
    op.drop_constraint(None, 'production_task_line_reports', type_='foreignkey')
    op.drop_column('production_task_line_reports', 'assignment_id')
    # ### end Alembic commands ###
