"""Заказ как единица планирования вместо недельного плана

Revision ID: 1eecd40abe12
Revises: b592ff114214
Create Date: 2026-08-10 17:05:53.689204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eecd40abe12'
down_revision: Union[str, Sequence[str], None] = 'b592ff114214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_material_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('planned_area_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # film_request_lines удаляется раньше weekly_plans — у неё FK на
    # weekly_plans.id (autogenerate иногда путает порядок, уже бывало в
    # этом проекте при ретрофите справочников).
    op.drop_table('film_request_lines')
    op.drop_index(op.f('ix_weekly_plans_week_start'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # weekly_plans создаётся раньше film_request_lines — у неё FK на
    # weekly_plans.id, родитель должен уже существовать.
    op.create_table('weekly_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('week_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('weekly_plans_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_plans_pkey'))
    )
    op.create_index(op.f('ix_weekly_plans_week_start'), 'weekly_plans', ['week_start'], unique=False)
    op.create_table('film_request_lines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('weekly_plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_area_m2', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thickness_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('film_request_lines_color_id_fkey')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('film_request_lines_material_id_fkey')),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], name=op.f('film_request_lines_thickness_id_fkey')),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], name=op.f('film_request_lines_weekly_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('film_request_lines_pkey'))
    )
    op.drop_table('order_material_lines')
    # ### end Alembic commands ###
