"""nazvanie_detali_na_stroke_zadaniya

Revision ID: 310bacaa0e01
Revises: 6ecff206e3e4
Create Date: 2026-08-13 09:05:08.778332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310bacaa0e01'
down_revision: Union[str, Sequence[str], None] = '6ecff206e3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_task_lines', sa.Column('part_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_task_lines', 'part_name')
    # ### end Alembic commands ###
