"""Производственные задания

Revision ID: 352ee7df7bcc
Revises: 74b754832f3f
Create Date: 2026-08-12 14:41:25.636073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Тип area уже существует в БД (создан в исходной миграции) — при
# add_column/create_table sa.Enum(..., create_type=False) молча не
# срабатывает для новых таблиц вне исходного upgrade(), поэтому берём
# ENUM явно из диалекта postgresql с create_type=False.
AREA_ENUM = postgresql.ENUM(
    "OKUTKA_TSARGOVYKH", "SHCHITOVYE_DVERI", "TSELNOLISTOVYE_DVERI", name="area", create_type=False
)


# revision identifiers, used by Alembic.
revision: str = '352ee7df7bcc'
down_revision: Union[str, Sequence[str], None] = '74b754832f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


permissions_table = sa.table(
    "permissions",
    sa.column("code", sa.String),
    sa.column("name", sa.String),
    sa.column("section", sa.String),
)
role_permissions_table = sa.table(
    "role_permissions",
    sa.column("role_id", sa.Integer),
    sa.column("permission_id", sa.Integer),
)

# Права заводим без явных id — каталог прав больше не создаётся с нуля
# (как в 2efa87769c18), сиквенс permissions_id_seq продолжает с текущего
# максимума сам. role_id 4 = nachalnik_tsekha, role_id 3 = nachalnik_uchastka
# (см. ROLES/ROLE_PERMISSIONS в 2efa87769c18_гибкая_ролевая_модель_ролей_и_прав.py).
NEW_PERMISSIONS = [
    ("production_tasks.manage", "Модели продукции и производственные задания", "Производство"),
    ("production_tasks.view", "Просмотр производственных заданий своего участка", "Производство"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area', AREA_ENUM, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('area', AREA_ENUM, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_model_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('qty_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_task_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('quantity_pieces', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['production_tasks.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        permissions_table,
        [{"code": code, "name": name, "section": section} for code, name, section in NEW_PERMISSIONS],
    )
    conn = op.get_bind()
    manage_id = conn.execute(
        sa.text("SELECT id FROM permissions WHERE code = 'production_tasks.manage'")
    ).scalar_one()
    view_id = conn.execute(
        sa.text("SELECT id FROM permissions WHERE code = 'production_tasks.view'")
    ).scalar_one()
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": 4, "permission_id": manage_id},  # nachalnik_tsekha
            {"role_id": 3, "permission_id": view_id},  # nachalnik_uchastka
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM role_permissions WHERE permission_id IN "
        "(SELECT id FROM permissions WHERE code IN ('production_tasks.manage', 'production_tasks.view'))"
    )
    op.execute("DELETE FROM permissions WHERE code IN ('production_tasks.manage', 'production_tasks.view')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_task_lines')
    op.drop_table('production_tasks')
    op.drop_table('product_model_parts')
    op.drop_table('production_lines')
    op.drop_table('product_models')
    # ### end Alembic commands ###
