"""line_id_nullable_i_raspredelenie_po_liniyam

Revision ID: 459791221de1
Revises: 05ec7abf6a39
Create Date: 2026-08-13 09:50:26.567110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459791221de1'
down_revision: Union[str, Sequence[str], None] = '05ec7abf6a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_task_line_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_line_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_names', sa.String(length=255), nullable=False),
    sa.Column('quantity_pieces', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['production_lines.id'], ),
    sa.ForeignKeyConstraint(['task_line_id'], ['production_task_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('production_task_lines', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_task_lines', 'line_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('production_task_line_assignments')
    # ### end Alembic commands ###
