"""Аналоги SKU, фото плёнки, роль продажник

Revision ID: 48d83d644681
Revises: 1eecd40abe12
Create Date: 2026-08-11 08:10:49.690616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d83d644681'
down_revision: Union[str, Sequence[str], None] = '1eecd40abe12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Новое значение Postgres ENUM user_role — хранится .name Python-enum
    # ('PRODAZHNIK'), не .value ('prodazhnik'), как и в прошлых миграциях,
    # добавлявших значения ENUM (см. миграцию Донор_предложен).
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'PRODAZHNIK'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sku_analogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('analog_sku_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analog_sku_id'], ['material_skus.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['material_skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_id', 'analog_sku_id')
    )
    op.add_column('material_skus', sa.Column('photo_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_skus', 'photo_path')
    op.drop_table('sku_analogs')
    # ### end Alembic commands ###
