"""инвентаризация: InventorySession, новые типы событий

Revision ID: 52df6c9e5dec
Revises: 8b6927bde820
Create Date: 2026-08-07 13:54:00.538504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52df6c9e5dec'
down_revision: Union[str, Sequence[str], None] = '8b6927bde820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate не видит новые значения существующего Postgres
    # ENUM — добавляем вручную (нельзя в одном DDL-выражении с несколькими
    # значениями, поэтому по одному). Значение — это .name Python-enum
    # (как у остальных, например 'PRIHOD'), а не кириллический .value.
    for value in (
        "INVENTARIZATSIYA_PODTVERZHDENO",
        "INVENTARIZATSIYA_PEREMESHCHENO",
        "INVENTARIZATSIYA_IZLISHEK",
        "INVENTARIZATSIYA_NEDOSTACHA",
    ):
        op.execute(f"ALTER TYPE event_type ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.Enum('RACK', 'WAREHOUSE', 'MATERIAL_SKU', name='inventory_scope_type'), nullable=False),
    sa.Column('scope_ref_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'CLOSED', name='inventory_status'), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('material_events', sa.Column('inventory_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'material_events', 'inventory_sessions', ['inventory_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_events', type_='foreignkey')
    op.drop_column('material_events', 'inventory_session_id')
    op.drop_table('inventory_sessions')
    # ### end Alembic commands ###
