"""material_event_fk_ondelete_set_null

Revision ID: 61d24816b1b0
Revises: 1674fb9e6538
Create Date: 2026-08-13 16:57:19.668996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d24816b1b0'
down_revision: Union[str, Sequence[str], None] = '1674fb9e6538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('material_events_order_id_fkey'), 'material_events', type_='foreignkey')
    op.drop_constraint(op.f('material_events_production_task_line_id_fkey'), 'material_events', type_='foreignkey')
    op.create_foreign_key(None, 'material_events', 'orders', ['order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'material_events', 'production_task_lines', ['production_task_line_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_events', type_='foreignkey')
    op.drop_constraint(None, 'material_events', type_='foreignkey')
    op.create_foreign_key(op.f('material_events_production_task_line_id_fkey'), 'material_events', 'production_task_lines', ['production_task_line_id'], ['id'])
    op.create_foreign_key(op.f('material_events_order_id_fkey'), 'material_events', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
