"""razmer_detali_shirina_dlina_na_stroke_zadaniya

Revision ID: 6ecff206e3e4
Revises: 6ca5798b8b62
Create Date: 2026-08-13 08:02:51.578192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecff206e3e4'
down_revision: Union[str, Sequence[str], None] = '6ca5798b8b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_model_parts', sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('product_model_parts', sa.Column('length_m', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('production_task_lines', sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('production_task_lines', sa.Column('length_m', sa.Numeric(precision=12, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_task_lines', 'length_m')
    op.drop_column('production_task_lines', 'width_mm')
    op.drop_column('product_model_parts', 'length_m')
    op.drop_column('product_model_parts', 'width_mm')
    # ### end Alembic commands ###
