"""Мультисклад

Revision ID: 74b754832f3f
Revises: fcbcc8ebffef
Create Date: 2026-08-12 14:06:50.653747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b754832f3f'
down_revision: Union[str, Sequence[str], None] = 'fcbcc8ebffef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # Существующие стеллажи должны получить явную привязку к складу —
    # заводим склад по умолчанию и переносим на него все текущие стеллажи,
    # прежде чем сделать racks.warehouse_id обязательным полем.
    op.execute("INSERT INTO warehouses (name, is_active) VALUES ('Основной склад', true)")
    op.add_column('racks', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE racks SET warehouse_id = (SELECT id FROM warehouses WHERE name = 'Основной склад')"
    )
    op.alter_column('racks', 'warehouse_id', nullable=False)
    op.create_foreign_key(None, 'racks', 'warehouses', ['warehouse_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racks', type_='foreignkey')
    op.drop_column('racks', 'warehouse_id')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
