"""тип события Донор_предложен

Revision ID: 88ec67bc989d
Revises: e1cf0e1d6262
Create Date: 2026-08-07 14:40:55.517508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ec67bc989d'
down_revision: Union[str, Sequence[str], None] = 'e1cf0e1d6262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic autogenerate не видит новые значения существующего Postgres
    # ENUM — значение это .name Python-enum ('DONOR_PREDLOZHEN'), не
    # кириллический .value (см. миграцию инвентаризации, где это уже
    # ловили как баг).
    op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'DONOR_PREDLOZHEN'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
