"""retrofit: справочники атрибутов, SKU, macro-zone rules

Revision ID: 8b6927bde820
Revises: ef7b0d238d02
Create Date: 2026-08-07 13:33:14.128815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6927bde820'
down_revision: Union[str, Sequence[str], None] = 'ef7b0d238d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thicknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value_mm', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value_mm')
    )
    op.create_table('macro_zone_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('from_shelf', sa.Integer(), nullable=False),
    sa.Column('to_shelf', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('thickness_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=64), nullable=True),
    sa.Column('native_width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'color_id', 'thickness_id', 'manufacturer_id')
    )
    op.drop_table('cells')
    op.drop_table('shelves')
    op.add_column('film_request_lines', sa.Column('material_id', sa.Integer(), nullable=False))
    op.add_column('film_request_lines', sa.Column('color_id', sa.Integer(), nullable=False))
    op.add_column('film_request_lines', sa.Column('thickness_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'film_request_lines', 'thicknesses', ['thickness_id'], ['id'])
    op.create_foreign_key(None, 'film_request_lines', 'colors', ['color_id'], ['id'])
    op.create_foreign_key(None, 'film_request_lines', 'materials', ['material_id'], ['id'])
    op.drop_column('film_request_lines', 'material')
    op.drop_column('film_request_lines', 'thickness')
    op.drop_column('film_request_lines', 'color')
    op.add_column('material_events', sa.Column('material_sku_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_material_events_material_key'), table_name='material_events')
    op.create_index(op.f('ix_material_events_material_sku_id'), 'material_events', ['material_sku_id'], unique=False)
    op.create_foreign_key(None, 'material_events', 'material_skus', ['material_sku_id'], ['id'])
    op.drop_column('material_events', 'material_key')
    op.add_column('material_units', sa.Column('material_sku_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_material_units_color'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_manufacturer'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_material'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_thickness'), table_name='material_units')
    op.create_index(op.f('ix_material_units_material_sku_id'), 'material_units', ['material_sku_id'], unique=False)
    op.create_foreign_key(None, 'material_units', 'material_skus', ['material_sku_id'], ['id'])
    op.drop_column('material_units', 'manufacturer')
    op.drop_column('material_units', 'material')
    op.drop_column('material_units', 'color')
    op.drop_column('material_units', 'thickness')
    op.add_column('racks', sa.Column('shelf_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racks', 'shelf_count')
    op.add_column('material_units', sa.Column('thickness', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    op.add_column('material_units', sa.Column('color', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('material_units', sa.Column('material', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('material_units', sa.Column('manufacturer', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material_units', type_='foreignkey')
    op.drop_index(op.f('ix_material_units_material_sku_id'), table_name='material_units')
    op.create_index(op.f('ix_material_units_thickness'), 'material_units', ['thickness'], unique=False)
    op.create_index(op.f('ix_material_units_material'), 'material_units', ['material'], unique=False)
    op.create_index(op.f('ix_material_units_manufacturer'), 'material_units', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_material_units_color'), 'material_units', ['color'], unique=False)
    op.drop_column('material_units', 'material_sku_id')
    op.add_column('material_events', sa.Column('material_key', sa.VARCHAR(length=600), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'material_events', type_='foreignkey')
    op.drop_index(op.f('ix_material_events_material_sku_id'), table_name='material_events')
    op.create_index(op.f('ix_material_events_material_key'), 'material_events', ['material_key'], unique=False)
    op.drop_column('material_events', 'material_sku_id')
    op.add_column('film_request_lines', sa.Column('color', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('film_request_lines', sa.Column('thickness', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=False))
    op.add_column('film_request_lines', sa.Column('material', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'film_request_lines', type_='foreignkey')
    op.drop_constraint(None, 'film_request_lines', type_='foreignkey')
    op.drop_constraint(None, 'film_request_lines', type_='foreignkey')
    op.drop_column('film_request_lines', 'thickness_id')
    op.drop_column('film_request_lines', 'color_id')
    op.drop_column('film_request_lines', 'material_id')
    op.create_table('shelves',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rack_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('macro_zone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], name=op.f('shelves_rack_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shelves_pkey'))
    )
    op.create_table('cells',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shelf_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], name=op.f('cells_shelf_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cells_pkey'))
    )
    op.drop_table('material_skus')
    op.drop_table('macro_zone_rules')
    op.drop_table('thicknesses')
    op.drop_table('materials')
    op.drop_table('manufacturers')
    op.drop_table('colors')
    # ### end Alembic commands ###
