"""Архивирование стеллажей (is_active)

Revision ID: b592ff114214
Revises: 94453126d55d
Create Date: 2026-08-10 10:09:35.687517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b592ff114214'
down_revision: Union[str, Sequence[str], None] = '94453126d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default добавлен вручную — иначе NOT NULL упадёт на уже
    # существующих строках racks.
    op.add_column('racks', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('racks', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racks', 'is_active')
    # ### end Alembic commands ###
