"""strip_width_mm_na_detali_i_stroke_zadaniya

Revision ID: d7203067069a
Revises: 459791221de1
Create Date: 2026-08-13 11:45:36.638161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7203067069a'
down_revision: Union[str, Sequence[str], None] = '459791221de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_model_parts', sa.Column('strip_width_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('production_task_lines', sa.Column('strip_width_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_task_lines', 'strip_width_mm')
    op.drop_column('product_model_parts', 'strip_width_mm')
    # ### end Alembic commands ###
