"""ABC-анализ ширин, настройки расчётов

Revision ID: e1cf0e1d6262
Revises: 52df6c9e5dec
Create Date: 2026-08-07 14:30:43.960928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cf0e1d6262'
down_revision: Union[str, Sequence[str], None] = '52df6c9e5dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calc_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_useful_width_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('abc_recalc_period_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('width_abc_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('thickness_id', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('width_class', sa.Enum('A', 'B', 'C', name='width_class'), nullable=False),
    sa.Column('total_length_m', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['thickness_id'], ['thicknesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'color_id', 'thickness_id', 'width_mm')
    )
    op.create_index(op.f('ix_width_abc_classes_color_id'), 'width_abc_classes', ['color_id'], unique=False)
    op.create_index(op.f('ix_width_abc_classes_material_id'), 'width_abc_classes', ['material_id'], unique=False)
    op.create_index(op.f('ix_width_abc_classes_thickness_id'), 'width_abc_classes', ['thickness_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_width_abc_classes_thickness_id'), table_name='width_abc_classes')
    op.drop_index(op.f('ix_width_abc_classes_material_id'), table_name='width_abc_classes')
    op.drop_index(op.f('ix_width_abc_classes_color_id'), table_name='width_abc_classes')
    op.drop_table('width_abc_classes')
    op.drop_table('calc_settings')
    # ### end Alembic commands ###
