"""initial schema

Revision ID: ef7b0d238d02
Revises: 
Create Date: 2026-08-07 11:27:29.417264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7b0d238d02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=True)
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('ROLL', 'STRIP', name='rack_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racks_code'), 'racks', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('NACHALNIK_TSEKHA', 'NACHALNIK_UCHASTKA', 'OPERATOR_SKLADA', 'KLADOVSHCHIK', 'SNABZHENETS', 'LOGIST', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('area', sa.Enum('OKUTKA_TSARGOVYKH', 'SHCHITOVYE_DVERI', 'TSELNOLISTOVYE_DVERI', name='area'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('material_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('upd_number', sa.String(length=64), nullable=False),
    sa.Column('pallet_number', sa.String(length=64), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('PRINYAT', 'NA_KHRANENII', 'VYDAN_UCHASTKU', 'SPISAN', name='unit_status'), nullable=False),
    sa.Column('area', sa.Enum('OKUTKA_TSARGOVYKH', 'SHCHITOVYE_DVERI', 'TSELNOLISTOVYE_DVERI', name='area'), nullable=True),
    sa.Column('location_code', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['material_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_units_color'), 'material_units', ['color'], unique=False)
    op.create_index(op.f('ix_material_units_manufacturer'), 'material_units', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_material_units_material'), 'material_units', ['material'], unique=False)
    op.create_index(op.f('ix_material_units_thickness'), 'material_units', ['thickness'], unique=False)
    op.create_index(op.f('ix_material_units_upd_number'), 'material_units', ['upd_number'], unique=False)
    op.create_table('shelves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('macro_zone', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_week_start'), 'weekly_plans', ['week_start'], unique=False)
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_request_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_plan_id', sa.Integer(), nullable=False),
    sa.Column('material', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('planned_area_m2', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('material_key', sa.String(length=600), nullable=False),
    sa.Column('event_type', sa.Enum('PRIHOD', 'PRODOLNAYA_REZKA', 'RASKROY', 'VYDACHA_UCHASTKU', 'VOZVRAT', 'SPISANIE', 'PRIVYAZKA_K_ZAKAZU', 'SNYATIE_PRIVYAZKI', name='event_type'), nullable=False),
    sa.Column('area', sa.Enum('OKUTKA_TSARGOVYKH', 'SHCHITOVYE_DVERI', 'TSELNOLISTOVYE_DVERI', name='area'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('from_length', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('to_length', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('from_cell', sa.String(length=32), nullable=True),
    sa.Column('to_cell', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity_delta_m', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['material_units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_material_events_material_key'), 'material_events', ['material_key'], unique=False)
    op.create_index(op.f('ix_material_events_timestamp'), 'material_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_material_events_unit_id'), 'material_events', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_events_unit_id'), table_name='material_events')
    op.drop_index(op.f('ix_material_events_timestamp'), table_name='material_events')
    op.drop_index(op.f('ix_material_events_material_key'), table_name='material_events')
    op.drop_table('material_events')
    op.drop_table('film_request_lines')
    op.drop_table('cells')
    op.drop_index(op.f('ix_weekly_plans_week_start'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_table('shelves')
    op.drop_index(op.f('ix_material_units_upd_number'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_thickness'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_material'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_manufacturer'), table_name='material_units')
    op.drop_index(op.f('ix_material_units_color'), table_name='material_units')
    op.drop_table('material_units')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_racks_code'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
