"""История цен поставщиков

Revision ID: fcbcc8ebffef
Revises: 2efa87769c18
Create Date: 2026-08-12 13:55:15.336370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbcc8ebffef'
down_revision: Union[str, Sequence[str], None] = '2efa87769c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('purchase_requests', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('purchase_requests', sa.Column('price_per_m2', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_foreign_key(None, 'purchase_requests', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_column('purchase_requests', 'price_per_m2')
    op.drop_column('purchase_requests', 'supplier_id')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
